In [1]:
import numpy

Función norm, que calcula la normal(o módulo) de un array

In [2]:
numpy.linalg.norm

<function numpy.linalg.linalg.norm(x, ord=None, axis=None, keepdims=False)>

Convensión para importar numpy

In [3]:
import numpy as np

Encontrar ayuda sobre cualquier tema

In [6]:
np.lookfor("solve")

Search results for 'solve'
--------------------------
numpy.linalg.solve
    Solve a linear matrix equation, or system of linear scalar equations.
numpy.linalg.lstsq
    Return the least-squares solution to a linear matrix equation.
numpy.linalg.tensorsolve
    Solve the tensor equation ``a x = b`` for x.
numpy.nditer.close
    close()
numpy.linalg._umath_linalg.solve
    solve the system a x = b, on the last two dimensions, broadcast to the rest.
numpy.linalg._umath_linalg.solve1
    solve the system a x = b, for b being a vector, broadcast in the outer dimensions.
numpy.distutils.misc_util.njoin
    Join two or more pathname components +
numpy.distutils.misc_util.minrelpath
    Resolve `..` and '.' from path.
numpy.distutils.system_info.UmfpackNotFoundError
    UMFPACK sparse solver (http://www.cise.ufl.edu/research/sparse/umfpack/)
numpy.shares_memory
    Determine if two arrays share memory
numpy.linalg.pinv
    Compute the (Moore-Penrose) pseudo-inverse of a matrix.
numpy.linalg.c

## **Funciones y constantes matemáticas**

In [7]:
np.e

2.718281828459045

In [8]:
np.pi

3.141592653589793

In [9]:
np.log(2)

0.6931471805599453

In [11]:
np.array([1, 2, 3])

array([1, 2, 3])

Los arrays de Numpy son homogéneos, todos sus elementos son del mismo tipo, esto quiere decir que python promocionará todos los elementos al tipo con más información, para acceder al tipo de dato de un array. Podemos usar el atributo dtype

In [15]:
a = np.array([1, 2, 3.0])
print(a.dtype)

float64


Pero se puede forzar el tipo de dato

In [18]:
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [19]:
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

También se puede convertir un array de un tipo a otro con el método .astype

In [24]:
a

array([1., 2., 3.])

In [25]:
a.astype(int)

array([1, 2, 3])